## tns-server docker compose file to work on traefik(reverse proxy)

version: '2'
services:
  tns:
    image: ${edgexfoundry}/system-tns-server-go/ubuntu_x86_64:latest
    container_name: tns-server
    volumes:
      - "/tns-server/data/db:/data/db"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip: /tns-server"
      - "traefik.port=48323"
    network_mode: "proxy"
...
