// Automatically generated by MockGen. DO NOT EDIT!
// Source: resource.go

package mock_resource

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *_MockCommandRecorder
}

// Recorder for MockCommand (not exported)
type _MockCommandRecorder struct {
	mock *MockCommand
}

func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &_MockCommandRecorder{mock}
	return mock
}

func (_m *MockCommand) EXPECT() *_MockCommandRecorder {
	return _m.recorder
}

func (_m *MockCommand) GetResourceInfo() (map[string]interface{}, error) {
	ret := _m.ctrl.Call(_m, "GetResourceInfo")
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCommandRecorder) GetResourceInfo() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetResourceInfo")
}

func (_m *MockCommand) GetPerformanceInfo() (map[string]interface{}, error) {
	ret := _m.ctrl.Call(_m, "GetPerformanceInfo")
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCommandRecorder) GetPerformanceInfo() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetPerformanceInfo")
}
