/*******************************************************************************
 * Copyright 2018 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *******************************************************************************/

// Code generated by MockGen. DO NOT EDIT.
// Source: topic.go

// Package mock_topic is a generated GoMock package.
package mock_topic

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCommand is a mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// Connect mocks base method
func (m *MockCommand) Connect(name string) error {
	ret := m.ctrl.Call(m, "Connect", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect
func (mr *MockCommandMockRecorder) Connect(name interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockCommand)(nil).Connect), name)
}

// Close mocks base method
func (m *MockCommand) Close() {
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close
func (mr *MockCommandMockRecorder) Close() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCommand)(nil).Close))
}

// CreateTopic mocks base method
func (m *MockCommand) CreateTopic(arg0 map[string]interface{}) error {
	ret := m.ctrl.Call(m, "CreateTopic", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic
func (mr *MockCommandMockRecorder) CreateTopic(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockCommand)(nil).CreateTopic), arg0)
}

// ReadTopicAll mocks base method
func (m *MockCommand) ReadTopicAll() ([]map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "ReadTopicAll")
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadTopicAll indicates an expected call of ReadTopicAll
func (mr *MockCommandMockRecorder) ReadTopicAll() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTopicAll", reflect.TypeOf((*MockCommand)(nil).ReadTopicAll))
}

// ReadTopic mocks base method
func (m *MockCommand) ReadTopic(name string, hierarchical bool) ([]map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "ReadTopic", name, hierarchical)
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadTopic indicates an expected call of ReadTopic
func (mr *MockCommandMockRecorder) ReadTopic(name, hierarchical interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTopic", reflect.TypeOf((*MockCommand)(nil).ReadTopic), name, hierarchical)
}

// DeleteTopic mocks base method
func (m *MockCommand) DeleteTopic(name string) error {
	ret := m.ctrl.Call(m, "DeleteTopic", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopic indicates an expected call of DeleteTopic
func (mr *MockCommandMockRecorder) DeleteTopic(name interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockCommand)(nil).DeleteTopic), name)
}
